<?php include "header.php" ?>
<div id="heading">
  <h1>Ideas above stations</h1>
  <h2>By Fiona Shipwright</h2>
</div>

<p>It was a [dayofweek] evening as I disembarked the train at [train station|1], getting on the train at that glass and metal canopy which has served so many different incarnations in a city which itself has also served so many different incarnations.</p>

<p>I proceeded down from the tracks into the depths of the station, still keenly aware of the great differences between this terminal and, the nearby one at [train station|2], [train station|2|street].</p>

<p>I was heading towards [museum|1], and as the weather changed from [weather] to well, even more [weather], I thought nothing of the fact that no one was seemed to be around. I was heading to the museum to meet with the curator about possibly working together in the future.</p>

<p>I was allowing my powers of concentration to be temporarily taken over by a particularly absorbing playlist, chosen specifically for this [weather] weather, thereby allow a perfect little aestheticisation of my humble everyday experience. Recently I had given this mechanism – the &lsquo;personal music video effect&rsquo; –  and how it affected my perception of [museum|1|city] a lot of thought. Was it very different to my experience walking around [forest|1] last [monthofyear]? So engrossed was I in such thoughts that it was with a start that I realised a paper missile had just landed upon the pavement a few steps in front of me.</p>

<p>I hadn&rsquo;t caught anything in my peripheral vision and it seemed that could only have come from a great height. This seemed fairly unlikely but not entirely unreasonable in a city like [museum|1|city] given the average roof height.</p>

<p>I picked up the paper, ready to swing round and hand it back in a hail of polite stammering to whoever had jettisoned it. But all was still. There was no one there. I looked around. This was a particularly in-between stretch of the city, a sort of non-place which bridged the areas of [plaza|1] and [town hall|1] by means of vastly underused main road. Indeed, a funny place for the [museum|1] to even be located. With no claimants forthcoming I unscrunched the ball of paper. It was a map. In another story, I would perhaps be at the start of a grand tale involving curious quests and treasure chests. For this story however, nothing so pirate-esque. It was a transport map. One I had seen a thousand times before. But, curiously, it was covered in annotations and not entirely useful ones at first glance. There seemed to be nothing relating to a specific journey or station or line. There was in fact nothing noted around [subway station|1] or the [bus line|1], both of which were nearby.</p>

<p>The artist, whoever they may be, seemed to have sketched something akin to a city-plan over the skeleton of the transport lines. But whilst it bore the same rough shape of [city|1] it was not an incarnation of the city that I recognised. Buildings such as the [zoo|1], [embassy|1], and [airport|1] did make an appearance, as did green spaces such as [green space|1], [park|1] and the [lake|1], but these were all surrounded by clusters of much smaller structures. They seemed to be too small to be single houses, yet far too big to represent a crowd of people. A network of estuaries criss-crossed the map, broad enough to give the suggestion of motorways, yet if this were the case they were entirely inappropriate to the context. One broad artery began in [neighborhood|1], sweeping across [neighbourhood|2], before finding what can only be described as an unsatisfactory end point in the depths of [neighborhood|3].</p>

<p>It suddenly occurred to me that I had been standing in the [weather] staring at the map for quite some time. If anyone nearby did want to seize back ownership, they were either very shy or now very far away. Realising that it was nearly [hours12] and I was now late, I re-scrunched the piece of paper (it seemed quicker than folding it. Perhaps this is a fallacy), put it in my bag and carried on walking.</p>

<p>A short while later I was greeted at the door of the museum by the curator. I opened my mouth to tell her of my strange discovery before something stopped me – I think I wanted to keep it to myself. I was so distracted by thoughts of my new, precious piece of paper that it took a few seconds to comprehend her panic-stricken expression. &ldquo;I&rsquo;m afraid we can&rsquo;t meet today – I&rsquo;m so sorry – but we discovered this afternoon that some articles from our collection have gone missing. From the maps and drawing archives. The programme I wanted to speak to you about. Well, it was a little, er, off-piste so to speak. Hence the challenges with funding I mentioned in my email.&rdquo;</p>

<p>I suddenly felt the walls of the [gallery|1] bearing down upon me. I shifted myself so that my bag felt very firmly anchored over on my shoulder. She had said nothing so far to indicate any connection with my recent cartographical discovery but in the past few minutes I had felt myself become fiercely protective of my contraband. She took a disproportionately deep breath and went on.</p>

<p>&ldquo;I guess I can tell you as you would have been told anyway. Though ideally that would have been after the non-disclosure agreement. Anyway. The [museum|1|city] senate released some files to us. They had their own attempted break in during [monthofyear] and got spooked. So they gave this &lsquo;material&rsquo; to us. For safekeeping. The material is, well, how to say. It has been collected from police stations around the city, mainly from [Police Station|1]. How to put this briefly - sometimes, when there is a case which remains open for years and years... well...sometimes those involved ask for some &lsquo;alternative&rsquo; help.&rdquo;</p>

<p>&lsquo;Alternative&rsquo; help? At this point I was glad the meeting was no longer going ahead though wondered where this replacement impromptu one was going. I really wanted to get back to my flat, which given that it was on [museum|1|street], was far enough away. Suddenly she threw her hands up to her face and spoke very quickly. &ldquo;Sometimes people ask for, oh what do the police refer to them as, oh, &lsquo;extra-sensory-practitioners&rsquo; to help find things and they do drawings and maps and lots of thinking and it sounds strange because it is but not that strange really well it depends and then after the attempt the senate thought people would find out and be outragde at the use of public funds so they gave the material to us. If you store them in an art gallery then well, perhaps they become &lsquo;art&rsquo; and little less contentious.&rdquo;</p>

<p>It took me a minute to diffuse my distraction and actually hear what she had just said. &ldquo;I, er… wait, extra… do you mean psychics? You mean the police use psychics and they draw maps and you have some and now… wait, what?&rdquo;. &ldquo;Yes. And the [museum|1] really wanted to do an exhibition on illustration and communication over the years and we were struggling for donations for material and we thought well if we have these, why not use them somehow. Plus then the exhibition was due to travel to [country], thereby solving the problem of embarrassment for the government. Taking them away. They would be framed as &lsquo;outsider art&rsquo;.&rdquo; I was one third intrigued, one third embarrassed (I&rsquo;m not even sure who far) with a final third comprising of mild offense and an ominous sense of foreboding. &ldquo;What um, do these maps and drawings of [museum|1|city] look like?&rdquo;</p>

<p>&ldquo;Well all sorts, but the collection that has gone missing - well they would have particularly nice in the exhibition. They&rsquo;re drawn on top of subway maps.&rdquo;</p>
    
<?php include "footer.php" ?>