<?php include "header.php" ?>
<div id="heading">
  <h1>Old light</h1>
  <h2>By Filip Hn&#237;zdo</h2>
</div>
<p>People are leaving [Train station|1], stumbling out onto [Train station|1|street] like they usually do on a [dayofweek] like this one. Meeting people, stopping for muffins, tea, showers for twenty credits. {if -[dayofweek]==Sunday,-[dayofweek]==Saturday|The usual people leaving or arriving at work.  A typical [park|1|city] weekday|Some going out to see friends, others, like me, working at the weekend}.</p>
<p>A lady in a blue dress and white trainers dashes out to find herself in a random opening of the crowd. It’s almost like a stage with the {if -[hourstosunset]<15|sun glaring overhead to form a spotlight|lamp burning a few meters above her head to form a spotlight}, but no one in the audience has her attention but me. Perhaps a friend or lover seeking to cross the gaze she flicks dramatically in every direction.</p> <p>Over there. A red t-shirt, white trousers. Bobbing brown hair cut neatly to the centre of a back. They find each other, smile and meet as everyone else fades into the background.</p>
<p>I turn the telescope around to [park|1]. I realise that management probably won't like my choice as I glance at the two dials to the right of me, remembering I’ve got a job to do. But I stay there regardless, looking out over another [dayofweek] in [park|1|city].</p>
<p>[dayofmonth][dayofmonthsuffix] [monthofyear] [year|+23] on the top, and today's date, [dayofmonth][dayofmonthsuffix] [monthofyear] [year|+200] underneath, smaller for reference. Simon starts his shift in an hour and I’ve hardly taken any notes. I know I can bluff them from associated patterns of [dayofweek]s, stitch together memories or pretend if I need to but even the thought of it makes me feel cold. These are lives, not fiction. They deserve to be remembered.</p>
<p>There’s a third dial to the left but I try not to look at it too much. I know it’s why this whole thing is set up and why we’re all here. I don’t even need to look to picture its display.</p><p>That one counting-down number is a bigger part of my thoughts than the current date on days like this. I don’t know these people but know that most of them will be dead in a year, the rest in two and a half. I know that number to the minute.</p>
<p>[park|1] is filled with wildlife. The clouds have parted perfectly above it giving me a wide, all-encompassing view. I’m glad we got that part right eventually. I wish I could hear it. Pop on headphones and close my eyes to soak in the birdsong, lapping of artificially placed water and scurrying in the branches, giggles of the group tucked deep under a tree telling jokes. I could send it to the lab for processing. Get them to analyse vibrations in the picture, calculate around the missing information. But it never sounds as good as it should. I spend a lot of time in the library listening to field recordings but know I’ll run out eventually. Give it a year and it’s all we’ll ever have.</p>
<p>I must have zoned out. The telescope is focused on the top of a tree, a wasted shot they’d say. I twist the controls to zoom out quickly, catch a wider glimpse at [park|1|city]. But my hand stops at a tint of blue and red sat on a patch of grass. The two from the station. They have good taste, it's a nice park nowadays.</p>
<p>Arms reach out from the red t-shirt, then the blue dress, taking turns to point around. Both of their legs and feet follow and accidentally meet at the tip. I pan to see what they’re pointing at. A dog walker, a building in the distance, up. Up. The sky. Slightly along. To the left. The wheels of my chair slide slowly back as my hand reaches up to the glass. A fingertip and a bright smiling face line up perfectly with the centre of the screen. She’s looking straight at me.</p>
<p>I wait for some words but it’s just a smile, a look at each other and away.</p>
    
<?php include "footer.php" ?>